events {}

http {
  upstream dispatchers {
    server dispatcher1:8000 max_fails=2 fail_timeout=10s;
    server dispatcher2:8000 max_fails=2 fail_timeout=10s;
  }

  server {
    listen 80;
    location / {
      proxy_pass http://dispatchers;
    }
  }
}